
#' @title Validate Binomial data
#'
#' @description `inspect_data_binomial` checks if an object contains data that is eligible to have been generated by a Binomial distribution. This can be useful to validate inputs in user-defined functions.
#'
#' @param data,success  Arbitrary objects. `success` is meant to indicate the value of `data` that corresponds to a success.
#' @param warning_nas Logical vector of \code{\link[base]{length}} 1. If `TRUE` then the presence of `NA` or `NaN` values in `data` generates a warning.
#'
#' @details `inspect_data_binomial` conducts a series of tests to check if `data` is eligible to have been generated by a Binomial distribution. Namely, `inspect_data_binomial` checks if:
#' * `data` and `success` are `NULL` or empty.
#' * `data` and `success` are atomic and have an eligible data type (logical, integer, double, character).
#' * `data` has `NA` or `NaN` values.
#' * The number of levels is adequate.
#' * `success` has \code{\link[base]{length}} 1.
#' * `success` is `NA` or `NaN`.
#' * `success` is observed in `data`.
#'
#' @return `inspect_data_binomial` does not return any output. There are three possible outcomes:
#' * The call is silent if:
#'   * `data` is eligible to have been generated by a Binomial distribution and there are no `NA` or `NaN` values in `data`
#'   * `data` is eligible to have been generated by a Binomial distribution, there are some `NA` or `NaN` values in `data` and `warning_nas` is set to `FALSE`.
#' * An informative warning message is thrown if:
#'   * `data` is eligible to have been generated by a Binomial distribution, there are some `NA` or `NaN` values in `data` and `warning_nas` is set to `TRUE`.
#'   * `data` is eligible to have been generated by a Binomial distribution and `success` is not observed in `data`.
#' * An informative error message is thrown and the execution is stopped if `data` is not eligible to have been generated by a Binomial distribution.
#'
#' @examples
#' # Calls that pass silently:
#' x1 <- c(1, 0, 0, 1, 0)
#' x2 <- c(FALSE, FALSE, TRUE)
#' x3 <- c("yes", "no", "yes")
#' x4 <- factor(c("yes", "no", "yes"))
#' x5 <- c(1, 0, 0, 1, 0, NA)
#' inspect_data_binomial(x1, success = 1)
#' inspect_data_binomial(x2, success = TRUE)
#' inspect_data_binomial(x3, success = "yes")
#' inspect_data_binomial(x4, success = "yes")
#' inspect_data_binomial(x5, success = 1)
#' inspect_data_binomial(x5, success = 1, warning_nas = FALSE)
#'
#' # Calls that throw an informative warning message:
#' \dontrun{y1 <- c(1, 1, NA, 0, 0)}
#' \dontrun{y2 <- c(0, 0)}
#' \dontrun{inspect_data_binomial(y1, success = 1, warning_nas = TRUE)}
#' \dontrun{inspect_data_binomial(y2, success = 1)}
#'
#' # Calls that throw an informative error message:
#' \dontrun{inspect_data_binomial(NULL, 1)}
#' \dontrun{inspect_data_binomial(c(1,0), NULL)}
#' \dontrun{inspect_data_binomial(list(1,0), 1)}
#' \dontrun{inspect_data_binomial(c(1,0), list(1))}
#' \dontrun{inspect_data_binomial(numeric(0), 0)}
#' \dontrun{inspect_data_binomial(1, numeric(0))}
#' \dontrun{inspect_data_binomial(NaN, 1)}
#' \dontrun{inspect_data_binomial(NA, 1)}
#' \dontrun{inspect_data_binomial(c(1,0), NA)}
#' \dontrun{inspect_data_binomial(c(1,0), NaN)}
#' \dontrun{inspect_data_binomial(c(1,0), 2)}
#'
#' @export

inspect_data_binomial <- function(data, success, warning_nas = FALSE){

  inspect_true_or_false(warning_nas)

  data_output_name <- paste0("'", deparse(substitute(data)), "'")
  s_output_name <- paste0("'", deparse(substitute(success)), "'")

  if(is.null(data)){
    stop(paste("Invalid argument:", data_output_name, "is NULL."))
  }
  if(is.null(success)){
    stop(paste("Invalid argument:", s_output_name, "is NULL."))
  }
  if(isFALSE(is.atomic(data))){
    stop(paste("Invalid argument:", data_output_name, "must be atomic."))
  }
  if(length(data) == 0){
    stop(paste("Invalid argument:", data_output_name, "is empty."))
  }
  if(any(isFALSE(is.atomic(success)), isFALSE(length(success) == 1))){
    stop(paste("Invalid argument:", s_output_name, "must be atomic and have length 1."))
  }
  if(isFALSE(typeof(data) %in% c("logical", "integer", "double", "character"))){
    stop(paste("Invalid argument: the type of", data_output_name, "must be 'logical', 'integer', 'double' or 'character'."))
  }
  if(isFALSE(typeof(success) %in% c("logical","integer", "double", "character"))){
    stop(paste("Invalid argument: the type of", s_output_name, "must be 'logical', 'integer', 'double' or 'character'."))
  }
  if(all(is.na(data))){
    stop(paste("Invalid argument: all elements of",  data_output_name, "are NA or NaN."))
  }
  if(is.na(success)){
    stop(paste("Invalid argument:", s_output_name, "is NA or NaN"))
  }

  data_factor <- factor(data, levels = unique(c(levels(factor(success)), levels(factor(unique(data))))))

  if(isTRUE(nlevels(data_factor) > 2)){
    stop(paste("Invalid argument: there are more than two levels'."))
  }
  if(isTRUE(warning_nas)){
    if(any(is.na(data))){
      warning(paste("There are NA or NaN values in", paste0(data_output_name, ".")))
    }
  }
  if(isFALSE(success %in% unique(data))){
    warning(paste(s_output_name, "not observed in", paste0(data_output_name, ".")))
  }
}

#' @title Validate categorical data
#'
#' @description `inspect_data_multinomial` checks if an object is a numeric vector of data eligible to have been generated by a Multinomial distribution. This can be useful to validate inputs in user-defined functions.

inspect_data_multinomial <- function(x, warning_nas = FALSE){

  inspect_true_or_false(warning_nas)

  x_output_name <- deparse(substitute(x))

  if(is.null(x)){
    stop(paste("Invalid argument:", x_output_name, "is NULL."))
  }
  if(any(isFALSE(is.atomic(x)), isFALSE(is.vector(x)))){
    stop(paste("Invalid argument:", x_output_name, "must be an atomic vector."))
  }
  if(isFALSE(typeof(x) %in% c("double", "integer", "character"))){
    stop("Invalid argument: typeof(x) must be 'integer', 'double' or 'character'.")
  }
  if(length(x) == 0){
    stop(paste("Invalid argument:", x_output_name, "is empty."))
  }
  if(isFALSE(typeof(x) %in% c("integer", "double", "character"))){
    stop(paste("Invalid argument: the type of", x_output_name, "must be 'logical', 'integer', 'double' or 'character'."))
  }
  if(all(is.na(x))){
    stop(paste("Invalid argument: all elements of",  x_output_name, " are NA or NaN."))
  }
  if(isTRUE(warning_nas)){
    if(any(is.na(x))){
      warning(paste("There are NA or NaN values in", paste0(x_output_name, ".")))
    }
  }

}
